### ISSUE TITLE
Prop Types warning

### ISSUE THREAD

**Issue by ImADrafter** [planttheidea/react-billboardjs#28]
Hi! Using react-billboard I found this issue. It is recreated in these codeSandboxes

When you supply an object to tick.culling (C3 supports this, [reference](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4culling) ) you get the next warning:

```
Invalid prop `axis.x.tick.culling` of type `object` supplied to `BillboardChart`, expected `boolean`.
```
The attribute is applying anyway.

Looking into the shapes, I found [this](https://github.com/planttheidea/react-billboardjs/blob/e768e04edca496769a6542936fc9ee74bcbdcf8c/src/shapes.js#L69), wich should be the same, but, it is not working.

CodeSandBox with [cullingMax](https://codesandbox.io/s/vigorous-volhard-mukip)
CodeSandBox with [culling.max](https://codesandbox.io/s/headless-star-q7mms)

**Comment by planttheidea** [comment]
Ah so the prop types need to be updated, that's fine. I can update them soon, over the weekend at the latest.

Just to clarify something, since you mentioned that "the attribute applied anyway" ... PropTypes are soft validators, they notify when something doesn't match expectations but do not throw an error or prevent rendering. It's not specific to this library, but React as a whole.

**Comment by ImADrafter** [comment]
Thank you very much for your early answer. 

We are up to date with proptypes, but thank you for your clarification anyway!

So, since cullingMax is not applying (and doesn't seem to appear anywhere else in the code) will be removed?

**Comment by planttheidea** [comment]
As mentioned, I will update the PropTypes at my first opportunity, unless you are willing to do a PR (always welcome!).
