### ISSUE TITLE
Replace 'componentWillUpdate' to stop React warning about it

### ISSUE THREAD

**Issue by FjVillar** [planttheidea/react-billboardjs#34]
Hi, first of all, thanks to @planttheidea for this project and all the work that has been done here.

In my team we have recently upgraded React to `16.12.0` and since react `16.10` if I'm not wrong, react is throwing a warning message alerting about the future deprecation of the lifecycle methods 'componentWillUpdate' and others. 

The correct way to fix this it would be to replace this lifecycle with another if possible in `react-billboardjs` codebase. I think there is only one. Replacing will probably make more problems if it makes the logic to change.

The fastest way it would be to replace the name with the `UNSAFE_` prefix.

I'm out of time this days but I would find some time to do the fastest way for sure. 

What do you think about this @planttheidea ?

**Comment by planttheidea** [comment]
I think I can tackle this sometime over the next few days, but ideally I would like this to be done in a way that was not a breaking change. In all likelihood (because this is doing low-level DOM manipulation) I can convert this to being `componentDidUpdate` (in hindsight, not sure why I used `componentWillUpdate`). If I can't do this for some reason, I'll programmatically determine if I need to apply the `UNSAFE_` prefix (as this library currently supports React 15 as well).

Either way, shouldn't be crazy to do.

**Comment by planttheidea** [comment]
This should be fixed in `1.5.4`. Let me know if you have any more issues!
