### ISSUE TITLE
Cannot resolve dependency './propTypes'

### ISSUE THREAD

**Issue by zwagner86** [planttheidea/react-billboardjs#49]
Hi,

Using `react-billboardjs@next` and getting the following error trying to implement a chart:
`Cannot resolve dependency './propTypes' at '[my_project_path]/node_modules/react-billboardjs/dist/propTypes'`

Area of the error:
```js
if (process.env.NODE_ENV !== 'production') {
  BillboardChart.propTypes = require('./propTypes').default;
}

exports.default = BillboardChart;
```
Here is a screenshot of the package in my node_modules:
![Screen Shot 2021-02-25 at 11 57 58 AM](https://user-images.githubusercontent.com/4967196/109197275-67fbfd00-7762-11eb-8140-f150c64b363d.png)

Perhaps the production build of the library is not deployed?

**Comment by planttheidea** [comment]
Well the production build is the vet folder you show haha, so they are indeed built, however the conditional inclusion may not work as hoped in all cases. I'll try to update this when I can without the conditional inclusion.

**Comment by planttheidea** [comment]
So the goal in general was to provide a way to exclude the `propTypes` entirely in production, mainly to reduce bundle size. The original technique was obviously flawed, but it also did not leave the option in case people _want_ to keep those `propTypes` in production. I've updated the build scripts to be more conditional, so that by default `propTypes` are always included. I've also added [documentation about how to make use of the build without `propTypes`](https://github.com/planttheidea/react-billboardjs#production-usage) to accomplish the original goal.

Hopefully this works better for you, but if you have more issues let me know!
